
function remove {
   if [ -d "/media/fat/$1" ]; then
      echo "/media/fat/$1"
      rm -r "/media/fat/$1"
   fi
}

remove "_Asteroid"
remove "_Asteroids Deluxe"
remove "_Bagman"
remove "_Battle Zone"
remove "_Black Widow"
remove "_Botanic"
remove "_Breakout"
remove "_Canyon Bomber"
remove "_Centipede"
remove "_Crystal Castles"
remove "_Disc of Tron"
remove "_Dominos"
remove "_Food Fight"
remove "_Gang Wars"
remove "_Gauntlet"
remove "_Gauntlet II"
remove "_Gravitar"
remove "_Gravitar"
remove "_Indiana Jones"
remove "_Lunar Battle"
remove "_Lunar Lander"
remove "_Marble Madness"
remove "_Missile_Command"
remove "_Pickin"
remove "_Peter Pack Rat"
remove "_Pickin"
remove "_Red Baron"
remove "_Road Blasters"
remove "_Road Runner"
remove "_Sky Adventure"
remove "_Sky Soldiers"
remove "_Space Race"
remove "_Sprint 1"
remove "_Sprint 2"
remove "_Squash"
remove "_Subs"
remove "_Squash"
remove "_Subs"
remove "_Super Bagman"
remove "_Super Breakout"
remove "_Tetris (Atari)"
remove "_Time Soldiers"
remove "_Tron"
remove "_Vindicators part II"
remove "_Xevious"