

[update]
  main_mister=0
  mame_rom=1
  gnw_rom=1
  console_core=1

[console]
  psx=1
  s32x=1
  saturn=1
  sgb=1
  neogeo=1

[clean]
  console_mgl=1
  obsolete_core=1

[folder]
  folder_name="_Insert Coin"
  newest=1