

[update]
  main_mister=0
  mame_rom=1
  gnw_rom=1
  console_core=1
  #dualsdram=0 ; single SDRAM core
  #dualsdram=1 ; Dual SDRAM core
  #dualsdram=2 ; Both Single and Dual SDRAM cores
  dualsdram=0

[console]
  psx=1
  s32x=1
  saturn=1
  sgb=1
  neogeo=1

[clean]
  console_mgl=1
  obsolete_core=1

[folder]
  newest=1
  vertical=1
  horizontal=1
